services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - ./data/transmission/data:/config
      - ./data/downloads:/downloads #optional
      - ./data/watch/folder:/watch #optional
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/transmission/web/"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      mynet:
        ipv4_address: 172.28.1.10
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./data/qbittorrent/appdata:/config
      - ./data/downloads:/downloads #optional
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      mynet:
        ipv4_address: 172.28.1.11
    restart: unless-stopped
  transmission-to-qbittorrent:
    image: ghcr.io/albodin/transmission-to-qbittorrent:main
    container_name: transmission-to-qbittorrent
    environment:
      - ENVIRON_CONFIG=true
      - SKIP_CHECK=true
      - QBITTORRENT_HOST=172.28.1.11
      - QBITTORRENT_PORT=8080
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=adminadmin
      - TRANSMISSION_PROTOCOL=http
      - TRANSMISSION_HOST=172.28.1.10
      - TRANSMISSION_PORT=9091
      - TRANSMISSION_PATH=/transmission/rpc
      - TRANSMISSION_USERNAME=
      - TRANSMISSION_PASSWORD=
      - TRANSMISSION_TORRENT_DIR=/data/transmission/data/torrents
    depends_on:
      transmission:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
    volumes:
    #  - ./config.json:/app/config.json:ro
      - ./data:/data
    networks:
      mynet:
        ipv4_address: 172.28.1.12


networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16